const $=s=>document.querySelector(s); const app=$('#app');
const LS='badr-kids-state-v3', RDB='badr-kids-recordings-v1';
const state=JSON.parse(localStorage.getItem(LS)||'{"stars":0,"learned":{},"stories":{},"games":0}');
function save(){localStorage.setItem(LS,JSON.stringify(state))}
function toast(t){const d=document.createElement('div');d.className='toast';d.textContent='🐻 بدر: '+t;document.body.appendChild(d);setTimeout(()=>d.remove(),1800)}
const data={
 animals:[['lion','🦁','أسد','Lion','roar.mp3','الأسد هو ملك الغابة. قوي وشجاع.'],['tiger','🐯','نمر','Tiger','roar.mp3','النمر سريع وله خطوط جميلة.'],['elephant','🐘','فيل','Elephant','trumpet.mp3','الفيل كبير وله خرطوم طويل.'],['giraffe','🦒','زرافة','Giraffe','giraffe.mp3','الزرافة لها رقبة طويلة.'],['monkey','🐒','قرد','Monkey','monkey.mp3','القرد يحب اللعب والقفز.'],['bear','🐻','دب','Bear','roar.mp3','الدب كبير ولطيف في قصتنا.'],['rabbit','🐰','أرنب','Rabbit','squeak.mp3','الأرنب سريع ويحب الجزر.'],['fox','🦊','ثعلب','Fox','fox.mp3','الثعلب ذكي وهادئ.'],['horse','🐴','حصان','Horse','neigh.mp3','الحصان يجري بسرعة.'],['cow','🐮','بقرة','Cow','moo.mp3','البقرة تعطينا الحليب.'],['sheep','🐑','خروف','Sheep','baa.mp3','الخروف له صوف ناعم.'],['goat','🐐','ماعز','Goat','baa.mp3','الماعز يحب التسلق.'],['camel','🐪','جمل','Camel','camel.mp3','الجمل يعيش في الصحراء.'],['dog','🐶','كلب','Dog','woof.mp3','الكلب وفيّ ويحرس البيت.'],['cat','🐱','قطة','Cat','meow.mp3','القطة ناعمة وتحب اللعب.'],['chicken','🐔','دجاجة','Chicken','cluck.mp3','الدجاجة تضع البيض.'],['duck','🦆','بطة','Duck','quack.mp3','البطة تسبح في الماء.'],['fish','🐟','سمكة','Fish','bubbles.mp3','السمكة تعيش في الماء.'],['turtle','🐢','سلحفاة','Turtle','turtle.mp3','السلحفاة بطيئة وصبورة.'],['dolphin','🐬','دولفين','Dolphin','dolphin.mp3','الدولفين ذكي ويحب البحر.']],
 food:[['apple','🍎','تفاحة','Apple'],['banana','🍌','موز','Banana'],['orange','🍊','برتقال','Orange'],['grapes','🍇','عنب','Grapes'],['strawberry','🍓','فراولة','Strawberry'],['watermelon','🍉','بطيخ','Watermelon'],['cherry','🍒','كرز','Cherry'],['mango','🥭','مانجو','Mango'],['lemon','🍋','ليمون','Lemon'],['pomegranate','🍎','رمان','Pomegranate'],['tomato','🍅','طماطم','Tomato'],['cucumber','🥒','خيار','Cucumber'],['carrot','🥕','جزر','Carrot'],['potato','🥔','بطاطا','Potato'],['onion','🧅','بصل','Onion'],['corn','🌽','ذرة','Corn'],['lettuce','🥬','خس','Lettuce'],['pepper','🫑','فلفل','Pepper'],['peas','🟢','بازلاء','Peas'],['broccoli','🥦','بروكلي','Broccoli']],
 transport:[['car','🚗','سيارة','Car'],['bus','🚌','حافلة','Bus'],['truck','🚚','شاحنة','Truck'],['train','🚆','قطار','Train'],['plane','✈️','طائرة','Airplane'],['helicopter','🚁','مروحية','Helicopter'],['ship','🚢','سفينة','Ship'],['boat','⛵','قارب','Boat'],['bike','🚲','دراجة','Bicycle'],['motorcycle','🏍️','دراجة نارية','Motorcycle'],['police','🚓','سيارة شرطة','Police car'],['ambulance','🚑','سيارة إسعاف','Ambulance'],['fire','🚒','سيارة إطفاء','Fire truck'],['tractor','🚜','جرار','Tractor'],['excavator','🏗️','حفارة','Excavator'],['metro','🚇','مترو','Metro'],['tram','🚋','ترام','Tram'],['rocket','🚀','صاروخ','Rocket'],['balloon','🎈','منطاد','Balloon'],['space','🛸','مركبة فضائية','Spaceship']],
 colors:[['🔴','أحمر','Red'],['🔵','أزرق','Blue'],['🟢','أخضر','Green'],['🟡','أصفر','Yellow'],['🟠','برتقالي','Orange'],['🟣','بنفسجي','Purple'],['⚫','أسود','Black'],['⚪','أبيض','White'],['🟤','بني','Brown'],['🩷','وردي','Pink']],
 shapes:[['●','دائرة','Circle'],['■','مربع','Square'],['▲','مثلث','Triangle'],['▬','مستطيل','Rectangle'],['★','نجمة','Star'],['♥','قلب','Heart'],['⬭','بيضاوي','Oval'],['◆','معين','Diamond'],['☾','هلال','Crescent'],['⬟','خماسي','Pentagon']],
 arabic:'أ ب ت ث ج ح خ د ذ ر ز س ش ص ض ط ظ ع غ ف ق ك ل م ن هـ و ي'.split(' ').map((l,i)=>['ar'+i,l,l,'']),
 english:'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('').map((l,i)=>['en'+i,l,l,''])
};
const stories=[['الأرنب والسلحفاة','🐰',['كان الأرنب سريعاً جداً.','كانت السلحفاة تمشي بهدوء.','بدأ السباق بينهما.','نام الأرنب في الطريق.','واصلت السلحفاة السير.','وصلت السلحفاة أولاً.','تعلم الأرنب ألا يتكبر.']],['النملة والحمامة والصياد','🐜',['سقطت نملة صغيرة في الماء.','رأتها حمامة طيبة.','ألقت الحمامة ورقة قرب النملة.','صعدت النملة على الورقة ونجت.','جاء صياد يريد الإمساك بالحمامة.','قرصت النملة قدم الصياد.','طارت الحمامة وشكرت النملة.']],['التراب والماء','🌱',['كانت هناك بذرة صغيرة.','سقطت البذرة في التراب.','جاء الماء وسقاها بلطف.','بدأت البذرة تنمو.','خرجت نبتة خضراء.','كبرت النبتة وصارت زهرة.','شكرت الزهرة التراب والماء.']],['الأسد والفأر','🦁',['نام الأسد تحت الشجرة.','لعب فأر صغير قربه.','استيقظ الأسد وأمسك الفأر.','قال الفأر: سامحني يا أسد.','ترك الأسد الفأر يذهب.','وقع الأسد في شبكة.','ساعده الفأر وقطع الشبكة.']],['الغراب والثعلب','🦊',['كان الغراب يحمل قطعة جبن.','رآه الثعلب وقال: صوتك جميل.','فرح الغراب وفتح فمه.','سقطت قطعة الجبن.','تعلم الغراب ألا يصدق كل كلام جميل.']],['البذرة الصغيرة','🌻',['وجد بدر بذرة صغيرة.','وضعها في التراب.','سقاها كل يوم.','خرجت أوراق صغيرة.','كبرت وصارت زهرة جميلة.']],['رحلة قطرة ماء','💧',['نزلت قطرة ماء من السحابة.','سقطت على وردة عطشى.','فرحت الوردة كثيراً.','جرت القطرة إلى النهر.','ثم عادت إلى السماء مع الشمس.']],['الشجرة الكريمة','🌳',['كانت شجرة كبيرة في الحديقة.','أعطت الأطفال ظلاً جميلاً.','أعطت العصافير بيتاً آمناً.','قال بدر: شكراً أيتها الشجرة.']],['السحابة والمطر','☁️',['سارت سحابة بيضاء في السماء.','رأت أرضاً عطشى.','نزل المطر بهدوء.','فرحت الزهور والأشجار.']],['النحلة والزهور','🐝',['طارت نحلة صغيرة.','زارت زهرة حمراء.','ثم زهرة صفراء.','جمعت الرحيق وصنعت عسلاً حلواً.']]];
while(stories.length<30){let i=stories.length+1;stories.push([`قصة بدر القصيرة ${i}`,'🐻',[`خرج بدر في نزهة جميلة.`,`رأى شيئاً جديداً وتعلم اسمه.`,`قال بدر: التعلم ممتع.`,`عاد بدر سعيداً إلى البيت.`]])}
function nav(active){return `<div class="nav"><button class="${active==='home'?'on':''}" onclick="home()">🐻<br>الرئيسية</button><button class="${active==='games'?'on':''}" onclick="games()">🎮<br>الألعاب</button><button class="${active==='stories'?'on':''}" onclick="storiesPage()">📖<br>القصص</button><button class="${active==='ach'?'on':''}" onclick="achievements()">⭐<br>إنجازاتي</button><button onclick="parentPanel()">👨‍👩‍👧<br>الوالدان</button></div>`}
function layout(html,active='home'){app.innerHTML=`<main class="wrap">${html}</main>${nav(active)}`}
function speak(text,lang='ar-JO'){try{speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(String(text));u.lang=lang;u.rate=lang.startsWith('ar')?.82:.86;u.pitch=1.02;let vs=speechSynthesis.getVoices();let v=vs.find(x=>x.lang&&x.lang.toLowerCase().startsWith(lang.slice(0,2).toLowerCase()))||null;if(v)u.voice=v;speechSynthesis.speak(u)}catch(e){}}
if('speechSynthesis'in window){speechSynthesis.onvoiceschanged=()=>speechSynthesis.getVoices();setTimeout(()=>speechSynthesis.getVoices(),300)}
function audioKey(kind,id,field='ar'){return `${kind}:${id}:${field}`}
function openDB(){return new Promise((res,rej)=>{let r=indexedDB.open(RDB,1);r.onupgradeneeded=()=>r.result.createObjectStore('audios');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function putAudio(key,blob){let db=await openDB();return new Promise((res,rej)=>{let tx=db.transaction('audios','readwrite');tx.objectStore('audios').put(blob,key);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function getAudio(key){let db=await openDB();return new Promise((res,rej)=>{let tx=db.transaction('audios','readonly'),rq=tx.objectStore('audios').get(key);rq.onsuccess=()=>res(rq.result);rq.onerror=()=>rej(rq.error)})}
async function delAudio(key){let db=await openDB();return new Promise((res,rej)=>{let tx=db.transaction('audios','readwrite');tx.objectStore('audios').delete(key);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
let mediaRecorder=null, chunks=[], recKey='';
async function startRec(key){try{let stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];recKey=key;mediaRecorder=new MediaRecorder(stream);mediaRecorder.ondataavailable=e=>chunks.push(e.data);mediaRecorder.onstop=async()=>{await putAudio(recKey,new Blob(chunks,{type:'audio/webm'}));stream.getTracks().forEach(t=>t.stop());toast('تم حفظ التسجيل العربي');};mediaRecorder.start();toast('بدأ التسجيل... قل الكلمة بوضوح')}catch(e){toast('اسمح للميكروفون من إعدادات المتصفح')}}
function stopRec(){if(mediaRecorder&&mediaRecorder.state==='recording')mediaRecorder.stop()}
async function playRecordedOrSpeak(key,text){let b=await getAudio(key); if(b){new Audio(URL.createObjectURL(b)).play()} else speak(text,'ar-JO')}
async function playRec(key){let b=await getAudio(key); if(b)new Audio(URL.createObjectURL(b)).play(); else toast('لا يوجد تسجيل بعد')}
async function deleteRec(key){await delAudio(key);toast('تم حذف التسجيل')}
function home(){layout(`<div class="topbar"><button class="pill" onclick="parentPanel()">👨‍👩‍👧 الوالدان</button><button class="iconBtn" onclick="parentPanel()">⚙️</button></div><section class="hero"><div class="heroContent"><div><div class="logo">عالم <b>بدر</b></div><div class="subtitle">نتعلم ونلعب معاً</div></div><div class="badrBig"><span class="heroWave">👋</span></div></div></section><div class="sectionTitle">⭐ أقسام تعليمية مبهرة</div><div class="grid"><button class="tile" onclick="listPage('animals','الحيوانات','🐾')"><div class="emoji">🦁</div><b>الحيوانات</b><span>صور وأصوات</span></button><button class="tile" onclick="listPage('food','الفواكه والخضروات','🍎')"><div class="emoji">🍎</div><b>الفواكه والخضروات</b><span>عربي وإنجليزي</span></button><button class="tile" onclick="listPage('transport','وسائل النقل','🚗')"><div class="emoji">🚗</div><b>وسائل النقل</b><span>مركبات جميلة</span></button><button class="tile" onclick="listPage('colors','الألوان','🎨')"><div class="emoji">🎨</div><b>الألوان</b><span>تعلم باللمس</span></button><button class="tile" onclick="listPage('shapes','الأشكال','🔺')"><div class="emoji">🔺</div><b>الأشكال</b><span>دائرة ومربع</span></button><button class="tile" onclick="listPage('arabic','الحروف العربية','🔤')"><div class="emoji">أ ب</div><b>الحروف العربية</b><span>نطق وتسجيل</span></button><button class="tile" onclick="listPage('english','الحروف الإنجليزية','🔠')"><div class="emoji">A B</div><b>English Letters</b><span>Pronunciation</span></button><button class="tile" onclick="numbersPage()"><div class="emoji">123</div><b>الأرقام</b><span>0 إلى 20</span></button></div><div class="sectionTitle">🎮 ألعاب تعليمية ممتعة</div><div class="grid">${gameTiles()}</div>`,'home')}
function gameTiles(){return [['quizPic','ترتيب الحروف','🧩'],['countGame','الأرقام والعد','🎈'],['englishPic','التركيب والصور','🍎'],['bubbleLetters','اختر الحرف الصحيح','🐱'],['memoryGame','لعبة الذاكرة','🧠'],['quizSound','من أنا؟','🐻'],['colorGame','فقاعات الحروف','🎈'],['shapeGame','متاهة الحيوانات','🐰']].map(g=>`<button class="tile gameTile" onclick="${g[0]}()"><div class="emoji">${g[2]}</div><b>${g[1]}</b><span>اضغط وابدأ</span></button>`).join('')}
function listPage(kind,title,icon){let arr=data[kind];layout(`<div class="row space"><button class="back" onclick="home()">الرئيسية</button><span class="chip">${icon} ${title}</span></div><div class="grid">${arr.map((x,i)=>`<button class="tile" onclick="detail('${kind}',${i})"><div class="emoji">${x[1]}</div><b>${x[2]}</b><span>${x[3]||x[2]}</span></button>`).join('')}</div>`,'home')}
function detail(kind,i){let x=data[kind][i], key=audioKey(kind,x[0]||i,'ar');let animalBtn=(kind==='animals'&&x[4])?`<button class="btn sun" onclick="new Audio('assets/audio/animals/${x[4]}').play()">🐾 صوت الحيوان</button>`:'';layout(`<div class="row space"><button class="back" onclick="listPage('${kind}','${kind==='animals'?'الحيوانات':kind==='food'?'الفواكه والخضروات':kind==='transport'?'وسائل النقل':kind==='colors'?'الألوان':kind==='shapes'?'الأشكال':kind==='arabic'?'الحروف العربية':'الحروف الإنجليزية'}','')">رجوع</button><span class="chip">🐻 بدر معك</span></div><div class="wordAr">${x[2]}</div><div class="wordEn">${x[3]||''}</div><div class="scene"><div class="mainEmoji">${x[1]}</div></div><div class="card"><div class="infoBox">${x[5]||`اضغط على النطق، أو سجّل صوتك العربي ليصبح التطبيق بصوت بشري.`}</div><div class="actions"><button class="btn green" onclick="playRecordedOrSpeak('${key}','${x[2]}')">🔊 نطق عربي</button><button class="btn" onclick="speak('${x[3]||x[2]}','en-US')">🔊 English</button>${animalBtn}</div></div><div class="card recordPanel"><h3 class="center">🎙️ تسجيل صوتك بالعربي</h3><p class="center">اضغط تسجيل وقل: "${x[2]}"</p><div class="actions"><button class="btn pink" onclick="startRec('${key}')">🎙️ تسجيل</button><button class="btn sun" onclick="stopRec()">⏹️ إيقاف</button><button class="btn green" onclick="playRec('${key}')">▶️ تشغيل تسجيلي</button><button class="btn danger" onclick="deleteRec('${key}')">🗑️ حذف</button></div><div class="wavebar"></div></div><div class="thumbs">${data[kind].slice(0,10).map((t,j)=>`<button class="thumb" onclick="detail('${kind}',${j})">${t[1]}</button>`).join('')}</div>`,'home')}
function numbersPage(){let arr=Array.from({length:21},(_,i)=>['num'+i,String(i),String(i),String(i)]);data.numbers=arr;listPage('numbers','الأرقام','🔢')}
function storiesPage(){layout(`<div class="row space"><button class="back" onclick="home()">الرئيسية</button><span class="chip">📖 30 قصة قصيرة</span></div><div class="grid">${stories.map((s,i)=>`<button class="tile" onclick="story(${i},0)"><div class="emoji">${s[1]}</div><b>${s[0]}</b><span>${s[2].length} صفحات</span></button>`).join('')}</div>`,'stories')}
function story(i,p){let s=stories[i], pages=s[2], pct=Math.round((p+1)/pages.length*100), key=audioKey('story'+i,p,'ar');layout(`<div class="row space"><button class="back" onclick="storiesPage()">القصص</button><span class="chip">${p+1}/${pages.length}</span></div><div class="card"><div class="progress"><i style="width:${pct}%"></i></div><h2 class="title">${s[0]}</h2><div class="scene"><div class="mainEmoji">${s[1]}</div></div><p class="storyText">${pages[p]}</p><div class="actions"><button class="btn green" onclick="playRecordedOrSpeak('${key}','${pages[p]}')">🔊 اسمع الصفحة</button><button class="btn pink" onclick="startRec('${key}')">🎙️ سجل الصفحة</button><button class="btn sun" onclick="stopRec()">⏹️ إيقاف</button><button class="btn alt" onclick="playRec('${key}')">▶️ تسجيلي</button>${p>0?`<button class="btn alt" onclick="story(${i},${p-1})">السابق</button>`:''}${p<pages.length-1?`<button class="btn" onclick="story(${i},${p+1})">التالي</button>`:`<button class="btn sun" onclick="finishStory(${i})">أنهيت القصة ⭐</button>`}</div></div>`,'stories')}
function finishStory(i){if(!state.stories[i]){state.stories[i]=1;state.stars+=2;save()}toast('رائع! أنهيت القصة');storiesPage()}
function games(){layout(`<div class="sectionTitle">🎮 ألعاب تعليمية مفتوحة</div><div class="grid">${gameTiles()}</div>`,'games')}
function pick(a){return a[Math.floor(Math.random()*a.length)]}function shuffle(a){return [...a].sort(()=>Math.random()-.5)}function pool(){return [...data.animals,...data.food,...data.transport]}
function check(btn,ok,next){document.querySelectorAll('.qopt,.tile').forEach(b=>b.disabled=true);btn.classList.add(ok?'good':'bad'); if(ok){state.stars++;state.games++;save();speak('أحسنت','ar-JO');toast('إجابة صحيحة ⭐')}else speak('حاول مرة أخرى','ar-JO');let p=document.createElement('div');p.className='card center';p.innerHTML=`<button class="btn green" onclick="${next}()">السؤال التالي ▶</button><button class="btn alt" onclick="games()">رجوع للألعاب</button>`;$('.wrap').appendChild(p)}
function quizPic(){let ans=pick(pool()),opts=shuffle([ans,...shuffle(pool().filter(x=>x!==ans)).slice(0,3)]);layout(`<div class="row space"><button class="back" onclick="games()">الألعاب</button><button class="btn small" onclick="quizPic()">سؤال جديد</button></div><h2 class="title">👀 أين ${ans[2]}؟</h2><div class="card center"><button class="btn" onclick="speak('أين ${ans[2]}؟','ar-JO')">🔊 اسمع</button>${opts.map(o=>`<button class="btn qopt" onclick="check(this,${o===ans},'quizPic')"><span style="font-size:54px">${o[1]}</span><br>${o[2]}</button>`).join('')}</div>`,'games')}
function quizSound(){let ans=pick(pool()),opts=shuffle([ans,...shuffle(pool().filter(x=>x!==ans)).slice(0,3)]);layout(`<div class="row space"><button class="back" onclick="games()">الألعاب</button></div><h2 class="title">🔊 اسمع واختر</h2><div class="card center"><button class="btn sun" onclick="speak('${ans[2]}','ar-JO')">تشغيل الصوت</button>${opts.map(o=>`<button class="btn qopt" onclick="check(this,${o===ans},'quizSound')"><span style="font-size:54px">${o[1]}</span><br>${o[2]}</button>`).join('')}</div>`,'games');setTimeout(()=>speak(ans[2],'ar-JO'),400)}
function countGame(){let n=1+Math.floor(Math.random()*10),e=pick(['🍎','⭐','🐻','🚗','🍌']),opts=shuffle([n,n+1,Math.max(1,n-1),n+2].filter((v,i,a)=>a.indexOf(v)===i));layout(`<div class="row space"><button class="back" onclick="games()">الألعاب</button></div><h2 class="title">🔢 كم العدد؟</h2><div class="card center"><div style="font-size:42px;line-height:1.35">${e.repeat(n)}</div>${opts.map(o=>`<button class="btn qopt" onclick="check(this,${o===n},'countGame')">${o}</button>`).join('')}</div>`,'games')}
function bubbleLetters(){let letters=[...data.arabic.map(x=>x[1]),...data.english.map(x=>x[1])],ans=pick(letters),opts=shuffle([ans,...shuffle(letters.filter(x=>x!==ans)).slice(0,5)]);layout(`<div class="row space"><button class="back" onclick="games()">الألعاب</button></div><h2 class="title">🎈 اضغط على حرف: ${ans}</h2><div class="grid">${opts.map(o=>`<button class="tile" onclick="check(this,'${o}'==='${ans}','bubbleLetters')"><div style="font-size:60px;font-weight:1000">${o}</div></button>`).join('')}</div>`,'games')}
function englishPic(){let ans=pick(pool()),opts=shuffle([ans,...shuffle(pool().filter(x=>x!==ans)).slice(0,3)]);layout(`<div class="row space"><button class="back" onclick="games()">الألعاب</button></div><h2 class="title" style="direction:ltr">🇬🇧 ${ans[3]}</h2><div class="card center"><button class="btn green" onclick="speak('${ans[3]}','en-US')">🔊 English</button>${opts.map(o=>`<button class="btn qopt" onclick="check(this,${o===ans},'englishPic')"><span style="font-size:54px">${o[1]}</span><br>${o[2]}</button>`).join('')}</div>`,'games')}
function colorGame(){let ans=pick(data.colors),opts=shuffle([ans,...shuffle(data.colors.filter(x=>x!==ans)).slice(0,3)]);layout(`<div class="row space"><button class="back" onclick="games()">الألعاب</button></div><h2 class="title">🎨 أين لون ${ans[1]}؟</h2><div class="card center">${opts.map(o=>`<button class="btn qopt" onclick="check(this,${o===ans},'colorGame')"><span style="font-size:64px">${o[0]}</span><br>${o[1]}</button>`).join('')}</div>`,'games')}
function shapeGame(){let ans=pick(data.shapes),opts=shuffle([ans,...shuffle(data.shapes.filter(x=>x!==ans)).slice(0,3)]);layout(`<div class="row space"><button class="back" onclick="games()">الألعاب</button></div><h2 class="title">🔺 أين شكل ${ans[1]}؟</h2><div class="card center">${opts.map(o=>`<button class="btn qopt" onclick="check(this,${o===ans},'shapeGame')"><span style="font-size:64px">${o[0]}</span><br>${o[1]}</button>`).join('')}</div>`,'games')}
let mf=null,ml=false,found=0;function memoryGame(){let base=shuffle(pool()).slice(0,4),cards=shuffle([...base,...base]);mf=null;ml=false;found=0;layout(`<div class="row space"><button class="back" onclick="games()">الألعاب</button><button class="btn small" onclick="memoryGame()">خلط جديد</button></div><h2 class="title">🧠 ذاكرة الصور</h2><div class="memoryGrid">${cards.map(c=>`<button class="mem" data-k="${c[2]}" data-e="${c[1]}" onclick="memClick(this)">❔</button>`).join('')}</div>`,'games')}
function memClick(b){if(ml||b.classList.contains('done')||b===mf)return;b.textContent=b.dataset.e;if(!mf){mf=b;return}ml=true;if(mf.dataset.k===b.dataset.k){b.classList.add('done');mf.classList.add('done');mf=null;ml=false;found++;if(found>=4){state.stars+=2;state.games++;save();toast('فزت في الذاكرة ⭐')}}else setTimeout(()=>{b.textContent='❔';mf.textContent='❔';mf=null;ml=false},650)}
function achievements(){let learned=Object.keys(state.learned).length,st=Object.keys(state.stories).length;layout(`<h2 class="title">⭐ إنجازاتي</h2><div class="grid"><div class="card center"><div class="stars">${state.stars}</div><b>نجمة</b></div><div class="card center"><div class="stars">${learned}</div><b>عنصر تعلمته</b></div><div class="card center"><div class="stars">${st}</div><b>قصة مكتملة</b></div><div class="card center"><div class="stars">${state.games}</div><b>إجابة صحيحة</b></div></div><div class="card center"><div class="badrBig" style="margin:auto;width:150px"></div><p class="muted"><b>بدر فخور بك جداً!</b></p><button class="btn" onclick="speak('بدر فخور بك، أحسنت يا بطل','ar-JO')">🔊 اسمع بدر</button></div>`,'ach')}
function parentPanel(){layout(`<div class="row space"><button class="back" onclick="home()">الرئيسية</button><span class="chip">👨‍👩‍👧 الوالدان</span></div><div class="card"><h2 class="title">إعدادات مهمة</h2><p class="muted">أفضل نطق عربي مجاني هو التسجيل البشري. سجّل الكلمات والقصص من داخل كل صفحة، وسيشغل التطبيق تسجيلك بدل صوت الجهاز.</p><button class="btn" onclick="speak('مرحباً يا صديقي، أنا بدر الدب. أحسنت يا بطل','ar-JO')">اختبار نطق الجهاز</button><p class="muted">الصورة المبهرة في الصفحة الرئيسية موجودة داخل: assets/images/showcase.png</p></div>`,'home')}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});home();
